DjangoTalk/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),

]

blog/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from blog import views

urlpatterns = [
    # url(r'^$', views.post_list, name='post_list'),
    url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail, name='post_detail'),
    url(r'^translations/$', TemplateView.as_view(template_name='post/translations.html')),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils import timezone


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

    def populate_posts(self):
        for i in range(20):
            post = Post()
            post.title = 'Populated Post - {}'.format(i)
            post.slug = 'populated-post-{}'.format(i)
            post.author_id = 1
            post.body = 'Body of populated post {}'.format(i)
            post.status = 'published'
            post.save()

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=25, choices=STATUS_CHOICES, default='draft')

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.strftime('%m'),
                                                 self.publish.strftime('%d'),
                                                 self.slug])

blog/forms.py
from django import forms


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

blog/views.py
from django.contrib import messages
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
from django.utils.translation import ugettext_lazy as _
from django.views.generic import ListView

from blog.forms import EmailPostForm
from blog.models import Post


def post_list(request):
    all_posts = Post.published.all()

    paginator = Paginator(all_posts, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'post/list.html', {'posts': posts})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'post/list.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    return render(request, 'post/detail.html', {'post': post})


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            if cd['to'] == 'admin@myblog.com':
                messages.error(request, _('Please fill out the form and resubmit.'))
            else:
                send_mail(subject, message, 'admin@myblog.com', [cd['to']])
                sent = True

    else:
        form = EmailPostForm()
    return render(request, 'post/share.html', {'post': post,
                                               'form': form,
                                               'sent': sent})

blog/templates/post/detail.html
{% extends "base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
    <p><a href="{% url "blog:post_share" post.id %}">Share this post</a></p>
    {{ post.body|linebreaks }}
{% endblock %}

blog/templates/post/list.html
{% extends "base.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}
    <h1>My blog</h1>
    {% for post in posts %}
        <h2><a href="{{  post.get_absolute_url }}">{{ post.title }}</a></h2>
        <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}

    {% comment %}
    -- for manually handling pagination
    {% include "pagination.html" with page=posts %}
    {% endcomment %}
    {% include "pagination.html" with page=page_obj %}
{% endblock %}

blog/templates/post/share.html
{% extends "base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == "error" %}
                <p>{{ message }}</p>
            {% endif %}

            {% if message.tags == "success" %}
            {% endif %}

            {% if message.tags == "info" %}
            {% endif %}

        {% endfor %}
    {% endif %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>"{{ post.title }}" was successfully sent by e-mail.</p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}

blog/templates/post/translations.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
    <p>
        {% trans "Hello world" %}
    </p>
{% endblock %}